/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ApiKeyResponse model module.
* @module model/ApiKeyResponse
* @version 1.6.0
*/
export default class ApiKeyResponse {
    /**
    * Constructs a new <code>ApiKeyResponse</code>.
    * @alias module:model/ApiKeyResponse
    * @class
    * @param key {String} 
    * @param secret {String} 
    */

    constructor(key, secret) {
        
        
        this['key'] = key;
        this['secret'] = secret;
        
    }

    /**
    * Constructs a <code>ApiKeyResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ApiKeyResponse} obj Optional instance to populate.
    * @return {module:model/ApiKeyResponse} The populated <code>ApiKeyResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiKeyResponse();
                        
            
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} key
    */
    key = undefined;
    /**
    * @member {String} secret
    */
    secret = undefined;




}
