/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';

/**
* The BatchMessage model module.
* @module model/BatchMessage
* @version 1.6.0
*/
export default class BatchMessage {
    /**
    * Constructs a new <code>BatchMessage</code>.
    * SMS Message Batch
    * @alias module:model/BatchMessage
    * @class
    * @param sender {String} The sender of the message. Should be no longer than 11 characters for alphanumeric or 15 characters for numeric sender ID's. No spaces or special characters.
    * @param destinations {Array.<String>} Telephone numbers of each of the recipients
    * @param content {String} Message to send to the recipient
    */

    constructor(sender, destinations, content) {
        
        
        this['sender'] = sender;
        this['destinations'] = destinations;
        this['content'] = content;
        
    }

    /**
    * Constructs a <code>BatchMessage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BatchMessage} obj Optional instance to populate.
    * @return {module:model/BatchMessage} The populated <code>BatchMessage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchMessage();
                        
            
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
            }
            if (data.hasOwnProperty('destinations')) {
                obj['destinations'] = ApiClient.convertToType(data['destinations'], ['String']);
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('deliveryreporturl')) {
                obj['deliveryreporturl'] = ApiClient.convertToType(data['deliveryreporturl'], 'String');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiClient.convertToType(data['schedule'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('ttl')) {
                obj['ttl'] = ApiClient.convertToType(data['ttl'], BigDecimal);
            }
            if (data.hasOwnProperty('validity')) {
                obj['validity'] = ApiClient.convertToType(data['validity'], BigDecimal);
            }
        }
        return obj;
    }

    /**
    * The sender of the message. Should be no longer than 11 characters for alphanumeric or 15 characters for numeric sender ID's. No spaces or special characters.
    * @member {String} sender
    */
    sender = undefined;
    /**
    * Telephone numbers of each of the recipients
    * @member {Array.<String>} destinations
    */
    destinations = undefined;
    /**
    * Message to send to the recipient
    * @member {String} content
    */
    content = undefined;
    /**
    * The url to which we should POST delivery reports to for this message. If none is specified, we'll use the global delivery report URL that you've configured on your account page.
    * @member {String} deliveryreporturl
    */
    deliveryreporturl = undefined;
    /**
    * Date-time at which to send the batch. This is only used by the batch/schedule service.
    * @member {String} schedule
    */
    schedule = undefined;
    /**
    * An identifying label for the message, which you can use to filter and report on messages you've sent later. Ideal for campaigns. A maximum of 280 characters.
    * @member {String} tag
    */
    tag = undefined;
    /**
    * The number of minutes before the delivery report is deleted. Optional. Omit to prevent delivery report deletion. Integer.
    * @member {module:model/BigDecimal} ttl
    */
    ttl = undefined;
    /**
    * The optional number of minutes to attempt delivery before the message is marked as EXPIRED. Optional. The default is 2880 minutes. Integer.
    * @member {module:model/BigDecimal} validity
    */
    validity = undefined;




}
