/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreditsResponse model module.
 * @module model/CreditsResponse
 * @version 1.9.0
 */
class CreditsResponse {
    /**
     * Constructs a new <code>CreditsResponse</code>.
     * @alias module:model/CreditsResponse
     * @param credits {Number} The number of remaining credits on your SMS Works account. Floating point number.
     */
    constructor(credits) { 
        
        CreditsResponse.initialize(this, credits);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, credits) { 
        obj['credits'] = credits;
    }

    /**
     * Constructs a <code>CreditsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditsResponse} obj Optional instance to populate.
     * @return {module:model/CreditsResponse} The populated <code>CreditsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditsResponse();

            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreditsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreditsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreditsResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

CreditsResponse.RequiredProperties = ["credits"];

/**
 * The number of remaining credits on your SMS Works account. Floating point number.
 * @member {Number} credits
 */
CreditsResponse.prototype['credits'] = undefined;






export default CreditsResponse;

