/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';

/**
* The CreditsResponse model module.
* @module model/CreditsResponse
* @version 1.6.0
*/
export default class CreditsResponse {
    /**
    * Constructs a new <code>CreditsResponse</code>.
    * @alias module:model/CreditsResponse
    * @class
    * @param credits {module:model/BigDecimal} The number of remaining credits on your SMS Works account. Floating point number.
    */

    constructor(credits) {
        
        
        this['credits'] = credits;
        
    }

    /**
    * Constructs a <code>CreditsResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreditsResponse} obj Optional instance to populate.
    * @return {module:model/CreditsResponse} The populated <code>CreditsResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditsResponse();
                        
            
            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], BigDecimal);
            }
        }
        return obj;
    }

    /**
    * The number of remaining credits on your SMS Works account. Floating point number.
    * @member {module:model/BigDecimal} credits
    */
    credits = undefined;




}
