/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorModel from './ErrorModel';
import ExtendedErrorModelAllOf from './ExtendedErrorModelAllOf';

/**
 * The ExtendedErrorModel model module.
 * @module model/ExtendedErrorModel
 * @version 1.8.0
 */
class ExtendedErrorModel {
    /**
     * Constructs a new <code>ExtendedErrorModel</code>.
     * @alias module:model/ExtendedErrorModel
     * @implements module:model/ErrorModel
     * @implements module:model/ExtendedErrorModelAllOf
     * @param message {String} 
     * @param errorCode {Number} Numeric code used to identify the error. Integer.
     * @param status {String} 
     */
    constructor(message, errorCode, status) { 
        ErrorModel.initialize(this, message);ExtendedErrorModelAllOf.initialize(this, errorCode, status);
        ExtendedErrorModel.initialize(this, message, errorCode, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, errorCode, status) { 
        obj['message'] = message;
        obj['errorCode'] = errorCode;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ExtendedErrorModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExtendedErrorModel} obj Optional instance to populate.
     * @return {module:model/ExtendedErrorModel} The populated <code>ExtendedErrorModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtendedErrorModel();
            ErrorModel.constructFromObject(data, obj);
            ExtendedErrorModelAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('permanent')) {
                obj['permanent'] = ApiClient.convertToType(data['permanent'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExtendedErrorModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExtendedErrorModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ExtendedErrorModel.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

ExtendedErrorModel.RequiredProperties = ["message", "errorCode", "status"];

/**
 * @member {String} message
 */
ExtendedErrorModel.prototype['message'] = undefined;

/**
 * Numeric code used to identify the error. Integer.
 * @member {Number} errorCode
 */
ExtendedErrorModel.prototype['errorCode'] = undefined;

/**
 * @member {String} status
 */
ExtendedErrorModel.prototype['status'] = undefined;

/**
 * @member {Boolean} permanent
 */
ExtendedErrorModel.prototype['permanent'] = undefined;


// Implement ErrorModel interface:
/**
 * @member {String} message
 */
ErrorModel.prototype['message'] = undefined;
// Implement ExtendedErrorModelAllOf interface:
/**
 * Numeric code used to identify the error. Integer.
 * @member {Number} errorCode
 */
ExtendedErrorModelAllOf.prototype['errorCode'] = undefined;
/**
 * @member {String} status
 */
ExtendedErrorModelAllOf.prototype['status'] = undefined;
/**
 * @member {Boolean} permanent
 */
ExtendedErrorModelAllOf.prototype['permanent'] = undefined;




export default ExtendedErrorModel;

