/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';
import ErrorModel from './ErrorModel';

/**
* The ExtendedErrorModel model module.
* @module model/ExtendedErrorModel
* @version 1.6.0
*/
export default class ExtendedErrorModel {
    /**
    * Constructs a new <code>ExtendedErrorModel</code>.
    * @alias module:model/ExtendedErrorModel
    * @class
    * @extends module:model/ErrorModel
    * @param message {} 
    * @param errorCode {} Numeric code used to identify the error. Integer.
    * @param status {} 
    */

    constructor(message, errorCode, status) {
        ErrorModel.call(this, message);
        
        this['errorCode'] = errorCode;
        this['status'] = status;
        
    }

    /**
    * Constructs a <code>ExtendedErrorModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ExtendedErrorModel} obj Optional instance to populate.
    * @return {module:model/ExtendedErrorModel} The populated <code>ExtendedErrorModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtendedErrorModel();
            
            ErrorModel.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], BigDecimal);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('permanent')) {
                obj['permanent'] = ApiClient.convertToType(data['permanent'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * Numeric code used to identify the error. Integer.
    * @member {module:model/BigDecimal} errorCode
    */
    errorCode = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {Boolean} permanent
    */
    permanent = undefined;




}
