/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Login model module.
* @module model/Login
* @version 1.6.0
*/
export default class Login {
    /**
    * Constructs a new <code>Login</code>.
    * authorisation object
    * @alias module:model/Login
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Login</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Login} obj Optional instance to populate.
    * @return {module:model/Login} The populated <code>Login</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Login();
                        
            
            if (data.hasOwnProperty('customerid')) {
                obj['customerid'] = ApiClient.convertToType(data['customerid'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
        }
        return obj;
    }

    /**
    * Your customer ID, available from your account area at https://thesmsworks.co.uk/user/login
    * @member {String} customerid
    */
    customerid = undefined;
    /**
    * API Key, available from your account area at https://thesmsworks.co.uk/user/login
    * @member {String} key
    */
    key = undefined;
    /**
    * API Secret, available from your account area at https://thesmsworks.co.uk/user/login
    * @member {String} secret
    */
    secret = undefined;




}
