/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';

/**
* The MessageResponse model module.
* @module model/MessageResponse
* @version 1.6.0
*/
export default class MessageResponse {
    /**
    * Constructs a new <code>MessageResponse</code>.
    * @alias module:model/MessageResponse
    * @class
    * @param content {String} 
    * @param created {String} 
    * @param customerid {String} 
    * @param destination {module:model/BigDecimal} 
    * @param messageid {String} 
    * @param modified {String} 
    * @param schedule {String} 
    * @param status {String} 
    * @param sender {String} 
    * @param tag {String} 
    */

    constructor(content, created, customerid, destination, messageid, modified, schedule, status, sender, tag) {
        
        
        this['content'] = content;
        this['created'] = created;
        this['customerid'] = customerid;
        this['destination'] = destination;
        this['messageid'] = messageid;
        this['modified'] = modified;
        this['schedule'] = schedule;
        this['status'] = status;
        this['sender'] = sender;
        this['tag'] = tag;
        
    }

    /**
    * Constructs a <code>MessageResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MessageResponse} obj Optional instance to populate.
    * @return {module:model/MessageResponse} The populated <code>MessageResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageResponse();
                        
            
            if (data.hasOwnProperty('batchid')) {
                obj['batchid'] = ApiClient.convertToType(data['batchid'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('customerid')) {
                obj['customerid'] = ApiClient.convertToType(data['customerid'], 'String');
            }
            if (data.hasOwnProperty('deliveryreporturl')) {
                obj['deliveryreporturl'] = ApiClient.convertToType(data['deliveryreporturl'], 'String');
            }
            if (data.hasOwnProperty('destination')) {
                obj['destination'] = ApiClient.convertToType(data['destination'], BigDecimal);
            }
            if (data.hasOwnProperty('failurereason')) {
                obj['failurereason'] = ApiClient.convertToType(data['failurereason'], Object);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('keyword')) {
                obj['keyword'] = ApiClient.convertToType(data['keyword'], 'String');
            }
            if (data.hasOwnProperty('messageid')) {
                obj['messageid'] = ApiClient.convertToType(data['messageid'], 'String');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'String');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiClient.convertToType(data['schedule'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} batchid
    */
    batchid = undefined;
    /**
    * @member {String} content
    */
    content = undefined;
    /**
    * @member {String} created
    */
    created = undefined;
    /**
    * @member {String} customerid
    */
    customerid = undefined;
    /**
    * @member {String} deliveryreporturl
    */
    deliveryreporturl = undefined;
    /**
    * @member {module:model/BigDecimal} destination
    */
    destination = undefined;
    /**
    * @member {Object} failurereason
    */
    failurereason = undefined;
    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} identifier
    */
    identifier = undefined;
    /**
    * @member {String} keyword
    */
    keyword = undefined;
    /**
    * @member {String} messageid
    */
    messageid = undefined;
    /**
    * @member {String} modified
    */
    modified = undefined;
    /**
    * @member {String} schedule
    */
    schedule = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {String} sender
    */
    sender = undefined;
    /**
    * @member {String} tag
    */
    tag = undefined;




}
