/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MetaData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MetaData'));
  } else {
    // Browser globals (root is window)
    if (!root.TheSmsWorksApi) {
      root.TheSmsWorksApi = {};
    }
    root.TheSmsWorksApi.QueryMetadata = factory(root.TheSmsWorksApi.ApiClient, root.TheSmsWorksApi.MetaData);
  }
}(this, function(ApiClient, MetaData) {
  'use strict';




  /**
   * The QueryMetadata model module.
   * @module model/QueryMetadata
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>QueryMetadata</code>.
   * An array of objects containing metadata key/value pairs that have been saved on messages.
   * @alias module:model/QueryMetadata
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>QueryMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QueryMetadata} obj Optional instance to populate.
   * @return {module:model/QueryMetadata} The populated <code>QueryMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('schema')) {
        obj['schema'] = MetaData.constructFromObject(data['schema']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/MetaData} schema
   */
  exports.prototype['schema'] = undefined;



  return exports;
}));


