/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScheduledMessage from './ScheduledMessage';

/**
 * The ScheduledMessagesResponseMessage model module.
 * @module model/ScheduledMessagesResponseMessage
 * @version 1.8.0
 */
class ScheduledMessagesResponseMessage {
    /**
     * Constructs a new <code>ScheduledMessagesResponseMessage</code>.
     * @alias module:model/ScheduledMessagesResponseMessage
     */
    constructor() { 
        
        ScheduledMessagesResponseMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScheduledMessagesResponseMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScheduledMessagesResponseMessage} obj Optional instance to populate.
     * @return {module:model/ScheduledMessagesResponseMessage} The populated <code>ScheduledMessagesResponseMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduledMessagesResponseMessage();

            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ScheduledMessage.constructFromObject(data['schema']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScheduledMessagesResponseMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScheduledMessagesResponseMessage</code>.
     */
    static validateJSON(data) {
        // validate the optional field `schema`
        if (data['schema']) { // data not null
          ScheduledMessage.validateJSON(data['schema']);
        }

        return true;
    }


}



/**
 * @member {module:model/ScheduledMessage} schema
 */
ScheduledMessagesResponseMessage.prototype['schema'] = undefined;






export default ScheduledMessagesResponseMessage;

