/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ScheduledMessage model module.
* @module model/ScheduledMessage
* @version 1.6.0
*/
export default class ScheduledMessage {
    /**
    * Constructs a new <code>ScheduledMessage</code>.
    * the scheduled message content
    * @alias module:model/ScheduledMessage
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ScheduledMessage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ScheduledMessage} obj Optional instance to populate.
    * @return {module:model/ScheduledMessage} The populated <code>ScheduledMessage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduledMessage();
                        
            
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('destination')) {
                obj['destination'] = ApiClient.convertToType(data['destination'], 'String');
            }
            if (data.hasOwnProperty('destinations')) {
                obj['destinations'] = ApiClient.convertToType(data['destinations'], ['String']);
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiClient.convertToType(data['schedule'], 'String');
            }
        }
        return obj;
    }

    /**
    * The sender of the message. Should be no longer than 11 characters for alphanumeric or 15 characters for numeric sender ID's. No spaces or special characters.
    * @member {String} sender
    */
    sender = undefined;
    /**
    * Message to be sent to the recipient
    * @member {String} content
    */
    content = undefined;
    /**
    * For single scheduled messages, the mobile number of the recipient
    * @member {String} destination
    */
    destination = undefined;
    /**
    * For batch messages, the mobile numbers of each of the recipients
    * @member {Array.<String>} destinations
    */
    destinations = undefined;
    /**
    * Date-time at which to send the batch. This is only used by the batch/schedule service.
    * @member {String} schedule
    */
    schedule = undefined;




}
