/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BigDecimal from './BigDecimal';

/**
* The SendMessageResponse model module.
* @module model/SendMessageResponse
* @version 1.6.0
*/
export default class SendMessageResponse {
    /**
    * Constructs a new <code>SendMessageResponse</code>.
    * @alias module:model/SendMessageResponse
    * @class
    * @param messageid {String} 
    * @param status {String} 
    * @param credits {module:model/BigDecimal} The number of remaining credits on your SMS Works account. Floating point number.
    * @param creditsUsed {module:model/BigDecimal} The number of credits used to send the message. Floating point number.
    */

    constructor(messageid, status, credits, creditsUsed) {
        
        
        this['messageid'] = messageid;
        this['status'] = status;
        this['credits'] = credits;
        this['creditsUsed'] = creditsUsed;
        
    }

    /**
    * Constructs a <code>SendMessageResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SendMessageResponse} obj Optional instance to populate.
    * @return {module:model/SendMessageResponse} The populated <code>SendMessageResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendMessageResponse();
                        
            
            if (data.hasOwnProperty('messageid')) {
                obj['messageid'] = ApiClient.convertToType(data['messageid'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], BigDecimal);
            }
            if (data.hasOwnProperty('creditsUsed')) {
                obj['creditsUsed'] = ApiClient.convertToType(data['creditsUsed'], BigDecimal);
            }
        }
        return obj;
    }

    /**
    * @member {String} messageid
    */
    messageid = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * The number of remaining credits on your SMS Works account. Floating point number.
    * @member {module:model/BigDecimal} credits
    */
    credits = undefined;
    /**
    * The number of credits used to send the message. Floating point number.
    * @member {module:model/BigDecimal} creditsUsed
    */
    creditsUsed = undefined;




}
