/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendMessageResponse model module.
 * @module model/SendMessageResponse
 * @version 1.8.0
 */
class SendMessageResponse {
    /**
     * Constructs a new <code>SendMessageResponse</code>.
     * @alias module:model/SendMessageResponse
     * @param messageid {String} 
     * @param status {String} 
     * @param credits {Number} The number of remaining credits on your SMS Works account. Floating point number.
     * @param creditsUsed {Number} The number of credits used to send the message. Floating point number.
     */
    constructor(messageid, status, credits, creditsUsed) { 
        
        SendMessageResponse.initialize(this, messageid, status, credits, creditsUsed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, messageid, status, credits, creditsUsed) { 
        obj['messageid'] = messageid;
        obj['status'] = status;
        obj['credits'] = credits;
        obj['creditsUsed'] = creditsUsed;
    }

    /**
     * Constructs a <code>SendMessageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendMessageResponse} obj Optional instance to populate.
     * @return {module:model/SendMessageResponse} The populated <code>SendMessageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendMessageResponse();

            if (data.hasOwnProperty('messageid')) {
                obj['messageid'] = ApiClient.convertToType(data['messageid'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], 'Number');
            }
            if (data.hasOwnProperty('creditsUsed')) {
                obj['creditsUsed'] = ApiClient.convertToType(data['creditsUsed'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SendMessageResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SendMessageResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SendMessageResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['messageid'] && !(typeof data['messageid'] === 'string' || data['messageid'] instanceof String)) {
            throw new Error("Expected the field `messageid` to be a primitive type in the JSON string but got " + data['messageid']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

SendMessageResponse.RequiredProperties = ["messageid", "status", "credits", "creditsUsed"];

/**
 * @member {String} messageid
 */
SendMessageResponse.prototype['messageid'] = undefined;

/**
 * @member {String} status
 */
SendMessageResponse.prototype['status'] = undefined;

/**
 * The number of remaining credits on your SMS Works account. Floating point number.
 * @member {Number} credits
 */
SendMessageResponse.prototype['credits'] = undefined;

/**
 * The number of credits used to send the message. Floating point number.
 * @member {Number} creditsUsed
 */
SendMessageResponse.prototype['creditsUsed'] = undefined;






export default SendMessageResponse;

