/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TestResponse model module.
* @module model/TestResponse
* @version 1.6.0
*/
export default class TestResponse {
    /**
    * Constructs a new <code>TestResponse</code>.
    * @alias module:model/TestResponse
    * @class
    * @param message {String} 
    */

    constructor(message) {
        
        
        this['message'] = message;
        
    }

    /**
    * Constructs a <code>TestResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TestResponse} obj Optional instance to populate.
    * @return {module:model/TestResponse} The populated <code>TestResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestResponse();
                        
            
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} message
    */
    message = undefined;




}
