/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TokenResponse model module.
* @module model/TokenResponse
* @version 1.6.0
*/
export default class TokenResponse {
    /**
    * Constructs a new <code>TokenResponse</code>.
    * @alias module:model/TokenResponse
    * @class
    * @param token {String} 
    */

    constructor(token) {
        
        
        this['token'] = token;
        
    }

    /**
    * Constructs a <code>TokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TokenResponse} obj Optional instance to populate.
    * @return {module:model/TokenResponse} The populated <code>TokenResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenResponse();
                        
            
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} token
    */
    token = undefined;




}
