/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BatchMessage from '../model/BatchMessage';
import BatchMessageResponse from '../model/BatchMessageResponse';
import CancelledMessageResponse from '../model/CancelledMessageResponse';
import ErrorModel from '../model/ErrorModel';
import ExtendedErrorModel from '../model/ExtendedErrorModel';
import Message from '../model/Message';
import MessageResponse from '../model/MessageResponse';
import ScheduledBatchResponse from '../model/ScheduledBatchResponse';

/**
* BatchMessages service.
* @module api/BatchMessagesApi
* @version 1.8.0
*/
export default class BatchMessagesApi {

    /**
    * Constructs a new BatchMessagesApi. 
    * @alias module:api/BatchMessagesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the batchAnyPost operation.
     * @callback module:api/BatchMessagesApi~batchAnyPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BatchMessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Sends a collection of unique SMS messages. Batches may contain up to 5000 messages at a time.
     * @param {Array.<module:model/Message>} messages An array of messages
     * @param {module:api/BatchMessagesApi~batchAnyPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BatchMessageResponse}
     */
    batchAnyPost(messages, callback) {
      let postBody = messages;
      // verify the required parameter 'messages' is set
      if (messages === undefined || messages === null) {
        throw new Error("Missing the required parameter 'messages' when calling batchAnyPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['JWT'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json;charset=UTF-8'];
      let returnType = BatchMessageResponse;
      return this.apiClient.callApi(
        '/batch/any', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the batchBatchidGet operation.
     * @callback module:api/BatchMessagesApi~batchBatchidGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MessageResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all messages in a batch with the given batch ID
     * @param {String} batchid The ID of the batch you would like returned
     * @param {module:api/BatchMessagesApi~batchBatchidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MessageResponse>}
     */
    batchBatchidGet(batchid, callback) {
      let postBody = null;
      // verify the required parameter 'batchid' is set
      if (batchid === undefined || batchid === null) {
        throw new Error("Missing the required parameter 'batchid' when calling batchBatchidGet");
      }

      let pathParams = {
        'batchid': batchid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['JWT'];
      let contentTypes = [];
      let accepts = ['application/json;charset=UTF-8'];
      let returnType = [MessageResponse];
      return this.apiClient.callApi(
        '/batch/{batchid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the batchSchedulePost operation.
     * @callback module:api/BatchMessagesApi~batchSchedulePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ScheduledBatchResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Schedules a batch of SMS messages to be sent at the date time you specify
     * @param {module:model/BatchMessage} smsMessage Message properties
     * @param {module:api/BatchMessagesApi~batchSchedulePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ScheduledBatchResponse}
     */
    batchSchedulePost(smsMessage, callback) {
      let postBody = smsMessage;
      // verify the required parameter 'smsMessage' is set
      if (smsMessage === undefined || smsMessage === null) {
        throw new Error("Missing the required parameter 'smsMessage' when calling batchSchedulePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['JWT'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json;charset=UTF-8'];
      let returnType = ScheduledBatchResponse;
      return this.apiClient.callApi(
        '/batch/schedule', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the batchSendPost operation.
     * @callback module:api/BatchMessagesApi~batchSendPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BatchMessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send a single SMS message to multiple recipients.  Batches may contain up to 5000 messages at a time.
     * @param {module:model/BatchMessage} smsMessage Message properties
     * @param {module:api/BatchMessagesApi~batchSendPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BatchMessageResponse}
     */
    batchSendPost(smsMessage, callback) {
      let postBody = smsMessage;
      // verify the required parameter 'smsMessage' is set
      if (smsMessage === undefined || smsMessage === null) {
        throw new Error("Missing the required parameter 'smsMessage' when calling batchSendPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['JWT'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json;charset=UTF-8'];
      let returnType = BatchMessageResponse;
      return this.apiClient.callApi(
        '/batch/send', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the batchesScheduleBatchidDelete operation.
     * @callback module:api/BatchMessagesApi~batchesScheduleBatchidDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CancelledMessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cancels a scheduled SMS message
     * @param {String} batchid The ID of the batch you would like returned
     * @param {module:api/BatchMessagesApi~batchesScheduleBatchidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CancelledMessageResponse}
     */
    batchesScheduleBatchidDelete(batchid, callback) {
      let postBody = null;
      // verify the required parameter 'batchid' is set
      if (batchid === undefined || batchid === null) {
        throw new Error("Missing the required parameter 'batchid' when calling batchesScheduleBatchidDelete");
      }

      let pathParams = {
        'batchid': batchid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['JWT'];
      let contentTypes = [];
      let accepts = ['application/json;charset=UTF-8'];
      let returnType = CancelledMessageResponse;
      return this.apiClient.callApi(
        '/batches/schedule/{batchid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
