/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: support@thesmsworks.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheSmsWorksApi);
  }
}(this, function(expect, TheSmsWorksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheSmsWorksApi.OTPResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OTPResponse', function() {
    it('should create an instance of OTPResponse', function() {
      // uncomment below and update the code to test OTPResponse
      //var instance = new TheSmsWorksApi.OTPResponse();
      //expect(instance).to.be.a(TheSmsWorksApi.OTPResponse);
    });

    it('should have the property messageid (base name: "messageid")', function() {
      // uncomment below and update the code to test the property messageid
      //var instance = new TheSmsWorksApi.OTPResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new TheSmsWorksApi.OTPResponse();
      //expect(instance).to.be();
    });

    it('should have the property credits (base name: "credits")', function() {
      // uncomment below and update the code to test the property credits
      //var instance = new TheSmsWorksApi.OTPResponse();
      //expect(instance).to.be();
    });

    it('should have the property creditsUsed (base name: "creditsUsed")', function() {
      // uncomment below and update the code to test the property creditsUsed
      //var instance = new TheSmsWorksApi.OTPResponse();
      //expect(instance).to.be();
    });

    it('should have the property messageparts (base name: "messageparts")', function() {
      // uncomment below and update the code to test the property messageparts
      //var instance = new TheSmsWorksApi.OTPResponse();
      //expect(instance).to.be();
    });

  });

}));
