/**
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import ApiKeyResponse from './model/ApiKeyResponse';
import BatchMessage from './model/BatchMessage';
import BatchMessageResponse from './model/BatchMessageResponse';
import CancelledMessageResponse from './model/CancelledMessageResponse';
import CreditsResponse from './model/CreditsResponse';
import DeletedMessageResponse from './model/DeletedMessageResponse';
import ErrorModel from './model/ErrorModel';
import ExtendedErrorModel from './model/ExtendedErrorModel';
import Login from './model/Login';
import Message from './model/Message';
import MessageResponse from './model/MessageResponse';
import MetaData from './model/MetaData';
import Query from './model/Query';
import ScheduledBatchResponse from './model/ScheduledBatchResponse';
import ScheduledMessage from './model/ScheduledMessage';
import ScheduledMessageResponse from './model/ScheduledMessageResponse';
import ScheduledMessagesResponse from './model/ScheduledMessagesResponse';
import SendMessageResponse from './model/SendMessageResponse';
import TestResponse from './model/TestResponse';
import TokenResponse from './model/TokenResponse';
import AuthApi from './api/AuthApi';
import BatchMessagesApi from './api/BatchMessagesApi';
import CreditsApi from './api/CreditsApi';
import MessagesApi from './api/MessagesApi';
import UtilsApi from './api/UtilsApi';

/**
* The_SMS_Works_provides_a_low_cost_reliable_SMS_API_for_developers__Pay_only_for_delivered_texts_all_failed_messages_are_refunded_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TheSmsWorksApi = require('index'); // See note below*.
* var xxxSvc = new TheSmsWorksApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TheSmsWorksApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TheSmsWorksApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TheSmsWorksApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.6.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiKeyResponse model constructor.
     * @property {module:model/ApiKeyResponse}
     */
    ApiKeyResponse,

    /**
     * The BatchMessage model constructor.
     * @property {module:model/BatchMessage}
     */
    BatchMessage,

    /**
     * The BatchMessageResponse model constructor.
     * @property {module:model/BatchMessageResponse}
     */
    BatchMessageResponse,

    /**
     * The CancelledMessageResponse model constructor.
     * @property {module:model/CancelledMessageResponse}
     */
    CancelledMessageResponse,

    /**
     * The CreditsResponse model constructor.
     * @property {module:model/CreditsResponse}
     */
    CreditsResponse,

    /**
     * The DeletedMessageResponse model constructor.
     * @property {module:model/DeletedMessageResponse}
     */
    DeletedMessageResponse,

    /**
     * The ErrorModel model constructor.
     * @property {module:model/ErrorModel}
     */
    ErrorModel,

    /**
     * The ExtendedErrorModel model constructor.
     * @property {module:model/ExtendedErrorModel}
     */
    ExtendedErrorModel,

    /**
     * The Login model constructor.
     * @property {module:model/Login}
     */
    Login,

    /**
     * The Message model constructor.
     * @property {module:model/Message}
     */
    Message,

    /**
     * The MessageResponse model constructor.
     * @property {module:model/MessageResponse}
     */
    MessageResponse,

    /**
     * The MetaData model constructor.
     * @property {module:model/MetaData}
     */
    MetaData,

    /**
     * The Query model constructor.
     * @property {module:model/Query}
     */
    Query,

    /**
     * The ScheduledBatchResponse model constructor.
     * @property {module:model/ScheduledBatchResponse}
     */
    ScheduledBatchResponse,

    /**
     * The ScheduledMessage model constructor.
     * @property {module:model/ScheduledMessage}
     */
    ScheduledMessage,

    /**
     * The ScheduledMessageResponse model constructor.
     * @property {module:model/ScheduledMessageResponse}
     */
    ScheduledMessageResponse,

    /**
     * The ScheduledMessagesResponse model constructor.
     * @property {module:model/ScheduledMessagesResponse}
     */
    ScheduledMessagesResponse,

    /**
     * The SendMessageResponse model constructor.
     * @property {module:model/SendMessageResponse}
     */
    SendMessageResponse,

    /**
     * The TestResponse model constructor.
     * @property {module:model/TestResponse}
     */
    TestResponse,

    /**
     * The TokenResponse model constructor.
     * @property {module:model/TokenResponse}
     */
    TokenResponse,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The BatchMessagesApi service constructor.
    * @property {module:api/BatchMessagesApi}
    */
    BatchMessagesApi,

    /**
    * The CreditsApi service constructor.
    * @property {module:api/CreditsApi}
    */
    CreditsApi,

    /**
    * The MessagesApi service constructor.
    * @property {module:api/MessagesApi}
    */
    MessagesApi,

    /**
    * The UtilsApi service constructor.
    * @property {module:api/UtilsApi}
    */
    UtilsApi
};
